### ISSUE TITLE
Wayback Everywhere release notes

### ISSUE THREAD

**Issue by grahamperrin** [gkrishnaks/WaybackEverywhere-Firefox#36]
https://addons.mozilla.org/addon/wayback-everywhere/versions/

Please, did something happen around May/June 2018 that caused to you stop including release notes?

TIA

**Comment by gkrishnaks** [comment]
Hi, Yes I moved repository to Gitlab.com and started using Gitlabs CI CD pipeline to push new versions to AMO , chrome store and opera stores for commits to Master branch.

In gitlab's CI CD, I use Mozilla's 'web-ext' tool and it does not yet support attaching release notes when it pushes a package to AMO.  (web-ext sign command uploads package to AMO)

All individual release notes are available here : https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/tags  and also inside the addon where update.html loads to present to the user when their installed addon gets the update.

**Comment by grahamperrin** [comment]
Ah, thanks. 

Closing side note: 

- [Update AMO page to refer to GitLab instead of GitHub (#89) · Issues · Gokulakrishna / Wayback Everywhere - Firefox · GitLab](https://gitlab.com/gkrishnaks/WaybackEverywhere-Firefox/issues/89)
